language: cpp
compiler:
  - gcc
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - bison
            - flex
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev libboost-all-dev libllvm3.9v4
  - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - gcc -v
    - g++ -v
    - cd build
    - cmake ..
    - make

