language: cpp
compiler:
  - gcc
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - bison
            - flex
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo apt-get -qq update > apt.log
  - sudo apt-get install -y libxml2-dev libboost-all-dev libllvm3.9v4 >> apt.log
  - eval "${MATRIX_EVAL}"

    # CMake
  - wget http://www.cmake.org/files/v3.8/cmake-3.8.2.tar.gz
  - tar -xvzf cmake-3.8.2.tar.gz > tar.log
  - cd cmake-3.8.2/
  - ./configure 
  - make
  - sudo make install
  - sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
  - cmake --version
  - cd ..

script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - mkdir build
  - gcc -v
  - g++ -v
  - llvm-config --version
  - cd build
  - cmake ..
  - make
