#ifndef __PARSER__HPP__
#define __PARSER__HPP__

#include <operations/basic_operation.hpp>

namespace jawe {
/** \brief Operation phase that parses source code and generates AST.
 *
 * Currently, it uses parser generated by a system bison.
 */
class parser : public basic_operation {
public:
	void run() const;
};
}

#endif // __PARSER__HPP__
